    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"User"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
in
    #"Removed Duplicates"