let
    Source = MySQL.Database("localhost", "license_schema", [ReturnSingleDatabase=true]),
    license_schema_triggered_table = Source{[Schema="license_schema",Item="triggered_table"]}[Data],
    #"Added Custom1" = Table.AddColumn(license_schema_triggered_table, "DayOnly", each Text.From(DateTime.Date([DateTime]))),
    #"Removed Other Columns" = Table.SelectColumns(#"Added Custom1",{"DayOnly"}),
    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"DayOnly", type date}})
in
    #"Changed Type"